### ISSUE TITLE
Paola Karina 

### ISSUE THREAD

**Issue by PaolaKarina** [Ironhack-Data-Madrid-Febrero-2021/Hey-I-am-a-data-analyst#11]
https://github.com/PaolaKarina/PROYECTO-DATA.git

**Comment by WHYTEWYLL** [comment]
Hola Paola,

Como ya dijimos esto sera un breve recap
de lo que te dijimos durante la presentacion.
Que debiste haber apuntado, esto normalmente se daba
cuando son unas clases mas grandes y no da tiempo a ver
todos los proyectos.

En tu caso, te dijimos que estaba se notaba el trabajo!

- Pero a nivel de código si que hay cosillas a mejorar, y se puede 
refactorizar y no repetir tanto codigo.
- Faltaría esos .py con las funciones auxiliares, sin el nombre de funcioncitas.
- A nivel de organización, el tener un carpeta y todo ahi, es lo mismo que no tener 
la carpeta. OJO CON LA LIMPIEZA.
- Utiliza ese gitignore para no subir tanto archivo, oculto como los de visual o del jupyrer de checkpoiint.
- Falta mucho mas proceso mental, limpieza en los jupyter , el report final y como dijimos estructura. Casi mejor abarcar poco y bien.

Seguimos!
