### ISSUE TITLE
Marina Díez

### ISSUE THREAD

**Issue by Marina-Diez** [Ironhack-Data-Madrid-Febrero-2021/Hey-I-am-a-data-analyst#3]
https://github.com/Marina-Diez/MARINA-DIEZ--Hey-I-am-a-data-analyst--.git

**Comment by WHYTEWYLL** [comment]
Hola Marina,

Como ya dijimos esto sera un breve recap
de lo que te dijimos durante la presentacion.
En tu casa, no tenemos muchos que decir.
Muy buen trabajo!
