### ISSUE TITLE
Isabela Lantero

### ISSUE THREAD

**Issue by ilga5414** [Ironhack-Data-Madrid-Febrero-2021/Hey-I-am-a-data-analyst#9]
https://github.com/ilga5414/proyectoII

**Comment by WHYTEWYLL** [comment]
Hola Isabela,

Como ya dijimos esto sera un breve recap
de lo que te dijimos durante la presentacion.
Que debiste haber apuntado, esto normalmente se daba
cuando son unas clases mas grandes y no da tiempo a ver 
todos los proyectos.

- En tu caso,te dijimos que estaba bastante bien
pero a nivel de codigo si que hay cosillas a mejorar. 
- Faltaria esos .py con las funciones auxiliares.
- En cuanto a la tabla, y evitar ese ariesfado iter. Podemos utilizar 
la clase de la tabla para poder sacarla en vez de coger todas las 'a'.
Buscamos las etiquetas table, y podemos especificar su clase.

![image](https://user-images.githubusercontent.com/49686519/120475977-569e3e80-c3aa-11eb-9517-d92edc977d56.png)

Muy buen trabajo!
